# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tresemus_v2.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 54, 17))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 150, 54, 17))
        self.label_5.setObjectName("label_5")
        self.line_openfile_encrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.line_openfile_encrypt.setGeometry(QtCore.QRect(80, 60, 113, 25))
        self.line_openfile_encrypt.setObjectName("line_openfile_encrypt")
        self.line_savefile_encrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.line_savefile_encrypt.setGeometry(QtCore.QRect(80, 100, 113, 25))
        self.line_savefile_encrypt.setObjectName("line_savefile_encrypt")
        self.line_key = QtWidgets.QLineEdit(self.centralwidget)
        self.line_key.setGeometry(QtCore.QRect(330, 150, 113, 25))
        self.line_key.setObjectName("line_key")
        self.Button_open_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Button_open_encrypt.setGeometry(QtCore.QRect(230, 60, 80, 25))
        self.Button_open_encrypt.setObjectName("Button_open_encrypt")
        self.button_save_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_encrypt.setGeometry(QtCore.QRect(230, 100, 80, 25))
        self.button_save_encrypt.setObjectName("button_save_encrypt")
        self.line_openfile_decrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.line_openfile_decrypt.setGeometry(QtCore.QRect(550, 60, 113, 25))
        self.line_openfile_decrypt.setObjectName("line_openfile_decrypt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 60, 54, 17))
        self.label_3.setObjectName("label_3")
        self.line_savefile_decrypt = QtWidgets.QLineEdit(self.centralwidget)
        self.line_savefile_decrypt.setGeometry(QtCore.QRect(550, 100, 113, 25))
        self.line_savefile_decrypt.setObjectName("line_savefile_decrypt")
        self.button_save_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_decrypt.setGeometry(QtCore.QRect(700, 100, 80, 25))
        self.button_save_decrypt.setObjectName("button_save_decrypt")
        self.button_open_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_decrypt.setGeometry(QtCore.QRect(700, 60, 80, 25))
        self.button_open_decrypt.setObjectName("button_open_decrypt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 110, 54, 17))
        self.label_4.setObjectName("label_4")
        self.button_open_key = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_key.setGeometry(QtCore.QRect(340, 180, 80, 25))
        self.button_open_key.setObjectName("button_open_key")
        self.button_save_key = QtWidgets.QPushButton(self.centralwidget)
        self.button_save_key.setGeometry(QtCore.QRect(340, 220, 80, 25))
        self.button_save_key.setObjectName("button_save_key")
        self.button_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_encrypt.setGeometry(QtCore.QRect(90, 170, 91, 61))
        self.button_encrypt.setObjectName("button_encrypt")
        self.button_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.button_decrypt.setGeometry(QtCore.QRect(560, 160, 91, 61))
        self.button_decrypt.setObjectName("button_decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "OpenFile"))
        self.label_2.setText(_translate("MainWindow", "SaveFile"))
        self.label_5.setText(_translate("MainWindow", "Key"))
        self.Button_open_encrypt.setText(_translate("MainWindow", "Open"))
        self.button_save_encrypt.setText(_translate("MainWindow", "Save"))
        self.label_3.setText(_translate("MainWindow", "OpenFile"))
        self.button_save_decrypt.setText(_translate("MainWindow", "Save"))
        self.button_open_decrypt.setText(_translate("MainWindow", "Open"))
        self.label_4.setText(_translate("MainWindow", "SaveFile"))
        self.button_open_key.setText(_translate("MainWindow", "Open"))
        self.button_save_key.setText(_translate("MainWindow", "Save"))
        self.button_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.button_decrypt.setText(_translate("MainWindow", "Decrypt"))
